name: cd-github-pages

on:
  workflow_dispatch:
    inputs:
      description:
        description: description
        required: true
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.20.1'
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install npm dependencies
      run: yarn install --frozen-lockfile
    - name: Run build:prod
      run: yarn build:prod
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
