name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18.12.1'
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install npm dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint:js
      run: yarn lint:js
    - name: Run lint:style
      run: yarn lint:style
    - name: Run lint:pug
      run: yarn lint:pug
